/*
 * This file is auto-generated by the mixer utility.
 * Generated on 2025-12-28 07:16:55 UTC.
 *
 * Do not edit this file directly. Any changes will be lost.
 */
/* ============================ Pre definitions ============================= */
#define MIXED_FILE 1

/* =========================== Directory: include =========================== */
/* ============================== 00-config.h =============================== */
/*
 * This file is part of the Fast Networking.
 *
 * The Fast Networking Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The Fast Networking Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the Fast Networking Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


	#if defined(__linux__) || defined(__linux) && !defined(_POSIX_C_SOURCE)
		#define _POSIX_C_SOURCE 200112L
	#endif /* __linux__ */

	#if !defined(_GNU_SOURCE) && !defined(FN_NO_GNU_SOURCE)
		#define _GNU_SOURCE 1
	#endif /* !defined(_GNU_SOURCE) && !defined(FN_NO_GNU_SOURCE) */

	#if !defined(_GNU_SOURCE) && !defined(FN_NO_GNU_SOURCE)
		#define _GNU_SOURCE 1
	#endif /* !defined(_GNU_SOURCE) && !defined(FN_NO_GNU_SOURCE) */

	#if !defined(_BSD_SOURCE) && !defined(FN_NO_BSD_SOURCE)
		#define _BSD_SOURCE 1
	#endif /* !defined(_BSD_SOURCE) && !defined(FN_NO_BSD_SOURCE) */

	#if !defined(_DEFAULT_SOURCE) && !defined(FN_NO_DEFAULT_SOURCE)
		#define _DEFAULT_SOURCE 1
	#endif /* !defined(_DEFAULT_SOURCE) && !defined(FN_NO_DEFAULT_SOURCE) */

	/* Configurable options for multicast. */

	/* Version string. */
	#ifndef FN_VERSION_STRING
		/* Default version string. */
		#define FN_VERSION_STRING "1.0.0"
	#endif /* FN_VERSION_STRING */

	/* Copyright string. */
	#ifndef FN_COPYRIGHT_STRING
		#define FN_COPYRIGHT_STRING "Copyright (C) 2025 ChenPi11."
	#endif /* FN_COPYRIGHT_STRING */

	/* Number of Ctrl-C signals required to force exit. */
	#ifndef FN_FORCE_EXIT_CTRL_C_COUNT
		#define FN_FORCE_EXIT_CTRL_C_COUNT 10
	#endif /* FN_FORCE_EXIT_CTRL_C_COUNT */

	/* Multicast IPv4 address. */
	#ifndef MULTICAST_ADDR
		#define MULTICAST_ADDR "224.0.1.1"
	#endif /* MULTICAST_ADDR */

	/* Multicast IPv6 address. */
	#ifndef MULTICAST_ADDR6
		#define MULTICAST_ADDR6 "ff02::fb"
	#endif /* MULTICAST_ADDR6 */

	/* Multicast port. */
	#ifndef MULTICAST_PORT
		#define MULTICAST_PORT 5354
	#endif /* MULTICAST_PORT */

	/* DNS port. */
	#ifndef DNS_PORT
		#define DNS_PORT 8053
	#endif /* DNS_PORT */

	/* DNS IPv4 address. */
	#ifndef DNS_ADDR4
		#define DNS_ADDR4 "0.0.0.0"
	#endif /* DNS_ADDR4 */

	/* DNS IPv6 address. */
	#ifndef DNS_ADDR6
		#define DNS_ADDR6 "::"
	#endif /* DNS_ADDR6 */

	/* Logging level. */
	#ifndef LOGGING_LEVEL
		#define LOGGING_LEVEL 0
	#endif /* LOGGING_LEVEL */

	/* Logging format for default handler. %1 is SUBJECT, %2 is LEVEL, %3 is
	   TIME in hex, %4 is MESSAGE. */
	#ifndef LOGGING_DEFAULT_FORMAT
		#define LOGGING_DEFAULT_FORMAT "[%1 %2 0x%3] %4\n"
	#endif /* LOGGING_DEFAULT_FORMAT */

	/* Multicast broadcast interval in milliseconds. */
	#ifndef MULTICAST_BOARDCAST_INTERVAL_MS
		#define MULTICAST_BOARDCAST_INTERVAL_MS 5000
	#endif /* MULTICAST_BOARDCAST_INTERVAL_MS */

	/* Global configuration file path for Unix-like systems. */
	#ifndef CONFIG_GLOBAL_CONFIG_FILE_UNIX
		#define CONFIG_GLOBAL_CONFIG_FILE_UNIX "/etc/fn/fn.conf"
	#endif /* CONFIG_GLOBAL_CONFIG_FILE_UNIX */

	/* User configuration file path for Unix-like systems. */
	#ifndef CONFIG_USER_CONFIG_FILE_UNIX
		#define CONFIG_USER_CONFIG_FILE_UNIX "~/.fn.conf"
	#endif /* CONFIG_USER_CONFIG_FILE_UNIX */

	/* Environment variable name for configuration file path. */
	#ifndef CONFIG_ENV_CONFIG_FILE
		#define CONFIG_ENV_CONFIG_FILE "FN_CONFIG_FILE"
	#endif /* CONFIG_ENV_CONFIG_FILE */

	/* Multicast protocol version. */
	#ifndef MULTICAST_VERSION
		#define MULTICAST_VERSION 1
	#endif /* MULTICAST_VERSION */

	/* Maximum length of multicast domain name. */
	#ifndef MULTICAST_MAX_DOMAIN_LEN
		#define MULTICAST_MAX_DOMAIN_LEN 256
	#endif /* MULTICAST_MAX_DOMAIN_LEN */

	/* Whether to use IPv6. If IPv6 is not supported, it will be disabled. */
	#ifndef USE_IPv6
		#define USE_IPv6 1
	#endif /* USE_IPv6 */

	#ifndef HAS_WINDOWS
		#if defined(_WIN32) || defined(_WIN64)
			#define HAS_WINDOWS 1
		#else
			#define HAS_WINDOWS 0
		#endif /* defined(_WIN32) || defined(_WIN64) */
	#endif     /* HAS_WINDOWS */

	#ifndef HAS_UNIX
		#if defined(__unix) || defined(__unix__) || defined(unix)
			#define HAS_UNIX 1
		#else
			#define HAS_UNIX 0
		#endif /* defined(__unix) || defined(__unix__) || defined(unix) */
	#endif     /* HAS_UNIX */

	#ifndef HAS_SAFE_C_LIB
		#if defined(__STDC_LIB_EXT1__) || (_MSC_VER >= 1600)
			#define HAS_SAFE_C_LIB 1
		#else
			#define HAS_SAFE_C_LIB 0
		#endif /* defined(__STDC_LIB_EXT1__) || (_MSC_VER >= 1600) */
	#endif     /* HAS_SAFE_C_LIB */

	#if (defined(FNAPI) || defined(_FNAPI_EXPORT)) &&                          \
		!(defined(FNAPI) && defined(_FNAPI_EXPORT))
		#error Both FNAPI and _FNAPI_EXPORT must be defined or neither.
	#endif

	#undef WIN32_LEAN_AND_MEAN
	#define WIN32_LEAN_AND_MEAN 1
	#undef NOMINMAX
	#define NOMINMAX 1
	#undef VC_EXTRALEAN
	#define VC_EXTRALEAN 1

	#if !defined(FNAPI) && !defined(_FNAPI_EXPORT)
		#ifdef _MSC_VER
			#define FNAPI __declspec(dllimport)
			#define _FNAPI_EXPORT __declspec(dllexport)
		#elif defined(__GNUC__) && __GNUC__ >= 4
			#define FNAPI __attribute__((visibility("default")))
			#define _FNAPI_EXPORT __attribute__((visibility("default")))
		#elif defined(__clang__) && __clang__ >= 4
			#define FNAPI __attribute__((visibility("default")))
			#define _FNAPI_EXPORT __attribute__((visibility("default")))
		#else
			#define FNAPI
			#define _FNAPI_EXPORT
		#endif /* _MSC_VER */

		/* Fix FNAPI visibility for building. */
		#if defined(_BUILDING_FN) || defined(MIXED_FILE)
			#undef FNAPI
			#define FNAPI _FNAPI_EXPORT
		#endif /* defined(_BUILDING_FN) || defined(MIXED_FILE) */

	#endif /* !defined(FNAPI) && !defined(_FNAPI_EXPORT) */



/* ============================== 01-stdafx.h =============================== */

/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


	#include <ctype.h>  /* IWYU pragma: export */
	#include <errno.h>  /* IWYU pragma: export */
	#include <signal.h> /* IWYU pragma: export */
	#include <stdarg.h>
	#include <stddef.h>
	#include <stdio.h>  /* IWYU pragma: export */
	#include <stdlib.h> /* IWYU pragma: export */
	#include <string.h> /* IWYU pragma: export */
	#include <time.h>   /* IWYU pragma: export */

	#if HAS_WINDOWS
		#include <Windows.h>

		#include <WinSock2.h>

		#include <WS2tcpip.h>

		#include <basetsd.h>
		#include <io.h>

	#elif HAS_UNIX
		#include <arpa/inet.h>
		#include <ifaddrs.h>
		#include <net/if.h>
		#include <netdb.h>
		#include <netinet/in.h>
		#include <stdint.h>
		#include <sys/socket.h>
		#include <sys/types.h>
		#include <unistd.h>
	#else
		#error Unsupported platform. Defined HAS_UNIX to 1 to use POSIX.
	#endif /* HAS_WINDOWS */

	#if defined(_MSC_VER) || (HAS_WINDOWS && defined(__clang__))
		#pragma comment(lib, "ws2_32.lib")
	#endif /* _MSC_VER || (HAS_WINDOWS && defined(__clang__)) */

	#ifndef AF_INET6
		#undef USE_IPv6
		#define USE_IPv6 0
	#endif /* AF_INET6 */



/* ============================== 02-va_copy.h ============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* va_copy implementation for various platforms. */
#ifndef va_copy
	/* Prefer compiler provided forms first. */
	#ifdef __va_copy
		#define va_copy(dest, src) __va_copy((dest), (src))
	#elif defined(__GNUC__) && defined(__GNUC_MINOR__)
		#define va_copy(dest, src) __builtin_va_copy((dest), (src))
	#elif defined(_MSC_VER)
		/* MSVC's va_list is assignable on known targets. */
		#define va_copy(dest, src) ((dest) = (src))
	#else
		/* Last resort: memcpy the underlying object. Works on many real-world
		   impls, but strictly speaking C89 doesn't guarantee it's portable for
		   all va_list representations (e.g. if va_list is an array type). */
		#ifndef FN_ALLOW_UNSAFE_VA_COPY
			#define va_copy(dest, src) memcpy(&(dest), &(src), sizeof(va_list))
		#else
			#error No va_copy implementation available on this platform. \
			You should update to C99 or later, \
			or define FN_ALLOW_UNSAFE_VA_COPY to force an unsafe \
			memcpy-based implementation.
		#endif /* FN_ALLOW_UNSAFE_VA_COPY */
	#endif     /* __va_copy */
#endif         /* va_copy */


/* =============================== 03-bool.h ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Boolean type. */
typedef unsigned int UTIL_Bool;

/* Boolean values. */
enum UTIL_BoolValues
{
	/* False. */
	UTIL_FALSE = 0,
	/* True. */
	UTIL_TRUE = 1
};



/* ============================== 04-minmax.h =============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef UTIL_max
	/* Maximum of A and B. */
	#define UTIL_max(a, b) ((a) > (b) ? (a) : (b))
#endif /* UTIL_max */

#ifndef UTIL_min
	/* Minimum of A and B. */
	#define UTIL_min(a, b) ((a) < (b) ? (a) : (b))
#endif /* UTIL_min */


/* ============================= 05-register.h ============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef UTIL_register
#ifdef __cplusplus
	/* Register keyword. */
	#define UTIL_register
#else
	/* Register keyword. */
	#define UTIL_register register
#endif /* __cplusplus */
#endif /* UTIL_register */


/* ================================ 06-int.h ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


	/* Old Windows SDK don't provide some integer types. */
	#if HAS_WINDOWS
typedef SSIZE_T UTIL_SignedSize;
typedef unsigned char UTIL_UInt8; /* VC6.0 Does not define UINT8. */
typedef unsigned short UTIL_UInt16;
typedef UINT32 UTIL_UInt32;
typedef UINT64 UTIL_UInt64;
typedef UTIL_UInt64 UTIL_Time;
	#else
typedef ssize_t UTIL_SignedSize;
typedef uint8_t UTIL_UInt8;
typedef uint16_t UTIL_UInt16;
typedef uint32_t UTIL_UInt32;
typedef uint64_t UTIL_UInt64;
typedef UTIL_UInt64 UTIL_Time;
	#endif /* HAS_WINDOWS */

	/* Maximum value for UTIL_SignedSize. */
	#define UTIL_SSIZE_MAX                                                     \
		(UTIL_SignedSize)(                                                     \
			((UTIL_UInt64)1 << (sizeof(UTIL_SignedSize) * 8 - 1)) - 1)

	/* Maximum value for size_t. */
	#define UITL_SIZE_MAX (UTIL_UInt64)(~(UTIL_UInt64)0)


/* ============================== 07-string.h =============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Constant string type. */
typedef const char *UTIL_ConstString;

/* Mutable string buffer type. */
typedef char *UTIL_StringBuffer;



/* ================================ 08-exc.h ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Initialize EXC module. */
FNAPI extern void EXC_initialize(void);

/* Deinitialize EXC module. */
FNAPI extern void EXC_deinitialize(void);

/* Exception error categories. */
typedef enum EXC_ErrorCategory
{
	/* Libc error category. */
	EXC_CATEGORY_LIBC = 0,
	/* System error category. */
	EXC_CATEGORY_SYS,
	/* Network error category. */
	EXC_CATEGORY_NET,
	/* Error category for this program. */
	EXC_CATEGORY_FN
} EXC_ErrorCategory;

/* Exception error codes for this program. */
typedef enum EXC_Errors
{
	/* Success. */
	EFN_SUCCESS = 0,
	/* Capacity exceeded. */
	EFN_MAX_CAPACITY_EXCEEDED = 1,
	/* Try again. */
	EFN_TRY_AGAIN = 2,
	/* DNS compression pointer unsupported. */
	EFN_COMPRESSION_PTR_UNSUPPORTED = 3,
	/* Invalid hostname. */
	EFN_INVALID_HOSTNAME = 4,
	/* No interfaces joined the multicast group */
	EFN_NO_MULTICAST_JOINED = 5,
	/* Join request refused. */
	EFN_JOIN_REFUSED = 6,

	EFN_MAX
} EXC_Errors;

/* Exception error code. */
typedef struct EXC_ErrorCode
{
	/* Error code. */
	int code;
	/* Error category. */
	enum EXC_ErrorCategory category;
} EXC_ErrorCode;

/* Get last exception code with CATEGORY. */
FNAPI extern EXC_ErrorCode EXC_get_last_error(enum EXC_ErrorCategory category);

/* Clear last exception code with CATEGORY. */
FNAPI extern void EXC_clear_last_error(enum EXC_ErrorCategory category);

/* Get string description of error code. */
FNAPI extern UTIL_ConstString EXC_strerror(struct EXC_ErrorCode error);



/* =========================== 09-generic-types.h =========================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


	#if 0 /* Generic template. */
/* Result<$TYPE>. */
typedef struct RESULT_$TYPE
{
	UTIL_Bool has_value;
	union {
		EXC_ErrorCode error;
		$TYPE value;
	} result;
} RESULT_$TYPE;
FNAPI extern RESULT_$TYPE RESULT_error_$TYPE(int code, EXC_ErrorCategory category);
FNAPI extern RESULT_$TYPE RESULT_error_$TYPE_struct(EXC_ErrorCode error);
FNAPI extern RESULT_$TYPE RESULT_ok_$TYPE($TYPE value);
	#endif

/* Result<UTIL_SignedSize>. */
typedef struct RESULT_UTIL_SignedSize
{
	UTIL_Bool has_value;
	union {
		EXC_ErrorCode error;
		UTIL_SignedSize value;
	} result;
} RESULT_UTIL_SignedSize;
FNAPI extern RESULT_UTIL_SignedSize RESULT_error_UTIL_SignedSize(
	int code, EXC_ErrorCategory category);
FNAPI extern RESULT_UTIL_SignedSize RESULT_error_UTIL_SignedSize_struct(
	EXC_ErrorCode error);
FNAPI extern RESULT_UTIL_SignedSize RESULT_ok_UTIL_SignedSize(
	UTIL_SignedSize value);

/* Result<UTIL_Time>. */
typedef struct RESULT_UTIL_Time
{
	UTIL_Bool has_value;
	union {
		EXC_ErrorCode error;
		UTIL_Time value;
	} result;
} RESULT_UTIL_Time;
FNAPI extern RESULT_UTIL_Time RESULT_error_UTIL_Time(
	int code, EXC_ErrorCategory category);
FNAPI extern RESULT_UTIL_Time RESULT_error_UTIL_Time_struct(
	EXC_ErrorCode error);
FNAPI extern RESULT_UTIL_Time RESULT_ok_UTIL_Time(UTIL_Time value);

/* Result<size_t>. */
typedef struct RESULT_size_t
{
	UTIL_Bool has_value;
	union {
		EXC_ErrorCode error;
		size_t value;
	} result;
} RESULT_size_t;
FNAPI extern RESULT_size_t RESULT_error_size_t(int code,
											   EXC_ErrorCategory category);
FNAPI extern RESULT_size_t RESULT_error_size_t_struct(
	EXC_ErrorCode error);
FNAPI extern RESULT_size_t RESULT_ok_size_t(size_t value);

/* Result<UTIL_ConstString>. */
typedef struct RESULT_UTIL_ConstString
{
	UTIL_Bool has_value;
	union {
		EXC_ErrorCode error;
		UTIL_ConstString value;
	} result;
} RESULT_UTIL_ConstString;
FNAPI extern RESULT_UTIL_ConstString RESULT_error_UTIL_ConstString(
	int code, EXC_ErrorCategory category);
FNAPI extern RESULT_UTIL_ConstString RESULT_error_UTIL_ConstString_struct(
	EXC_ErrorCode error);
FNAPI extern RESULT_UTIL_ConstString RESULT_ok_UTIL_ConstString(
	UTIL_ConstString value);

/* Result<void>. */
typedef struct RESULT_Tag_void
{
	UTIL_Bool has_value;
	EXC_ErrorCode error;
} RESULT_void;
FNAPI extern RESULT_void RESULT_error_void(int code,
										   EXC_ErrorCategory category);
FNAPI extern RESULT_void RESULT_error_void_struct(EXC_ErrorCode error);
FNAPI extern RESULT_void RESULT_ok_void(void);

	#define RESULT_ERRNO(ResultType, category)                                 \
		RESULT_error_##ResultType##_struct(EXC_get_last_error(category))



/* =========================== 10-thread-local.h ============================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef UTIL_THREAD_LOCAL
	#if defined(_MSVC_LANG) && defined(__cplusplus)
		#define UTIL_CPP_STD _MSVC_LANG
	#elif defined(__cplusplus)
		#define UTIL_CPP_STD __cplusplus
	#endif /* defined(_MSVC_LANG) && defined(__cplusplus) */

	/* Use thread-local storage. Although this program is only single-thread. */
	#if UTIL_CPP_STD >= 201103L
		#define UTIL_THREAD_LOCAL thread_local
	#elif defined(_ISOC11_SOURCE) ||                                           \
		(defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L)
		#define UTIL_THREAD_LOCAL _Thread_local
	#elif defined(__GNUC__) || defined(__clang__) || defined(__ICCARM__) ||    \
		defined(__TINYC__) || defined(__INTEL_LLVM_COMPILER) ||                \
		defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ICPC)
		#define UTIL_THREAD_LOCAL __thread
	#elif defined(_MSC_VER)
		#define UTIL_THREAD_LOCAL __declspec(thread)
	#elif defined(thread_local)
		#define UTIL_THREAD_LOCAL thread_local
	#else
		#define UTIL_THREAD_LOCAL
	#endif

#endif /* UTIL_THREAD_LOCAL */


/* =============================== 11-utils.h =============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Initialize UTIL module. */
FNAPI extern void UTIL_initialize(void);

/* Duplicate memory block SRC of size N. Return NULL on error. */
FNAPI extern void *UTIL_memdup(const void *src, size_t n);

/* Duplicate string STR. Return NULL on error. */
FNAPI extern UTIL_StringBuffer UTIL_strdup(const char *src);

/* Print formatted string to BUFFER.*/
FNAPI extern RESULT_UTIL_SignedSize UTIL_vsprintf(UTIL_StringBuffer *buffer,
												  UTIL_ConstString fmt,
												  va_list args);

/* Get current time in milliseconds. */
FNAPI extern UTIL_Time UTIL_get_current_time_ms(void);

/* Sleep for MS milliseconds. */
FNAPI extern void UTIL_sleep_ms(UTIL_Time ms);

/* Timer structure. */
struct UTIL_Timer
{
	UTIL_Time start_time;  /* Start time in milliseconds. */
	UTIL_Time duration_ms; /* Duration in milliseconds. */
};

/* Start timer TIMER. */
FNAPI extern void UTIL_timer_start(struct UTIL_Timer *timer);

/* Reset timer TIMER. */
FNAPI extern void UTIL_timer_reset(struct UTIL_Timer *timer);

/* Get elapsed time in milliseconds since TIMER was started. */
FNAPI extern UTIL_Time UTIL_timer_elapsed_ms(struct UTIL_Timer *timer);

/* Check if TIMER has elapsed DURATION_MS milliseconds. Return UTIL_TRUE if yes,
   UTIL_FALSE if not. */
FNAPI extern UTIL_Bool UTIL_timer_ontime(struct UTIL_Timer *timer,
										 UTIL_Time duration_ms);

/* Compute CRC16-CCITT hash of string KEY. TABLE_SIZE_2POWER is the size of hash
   table (must be a power of 2). It MUST be a power of 2, or undefined behavior
   will occur. */
FNAPI extern UTIL_UInt16 UTIL_str_hash(UTIL_ConstString key,
									   UTIL_UInt16 table_size_2power);

/* Check if PATH is a file. Return UTIL_TRUE if yes, UTIL_FALSE if not. */
FNAPI extern UTIL_Bool UTIL_is_file(UTIL_ConstString path);

/* Convert string STR to unsigned base 10 integer. */
FNAPI extern RESULT_size_t UTIL_str_to_unsigned_base10(UTIL_ConstString str);

	/* Size of buffer required to store hex string of size_t. */
	#define SIZE_T_HEX_BUFSIZE (2 * sizeof(size_t) + sizeof(char))

/* Convert a size_t to hex string. Remove leading zeros. */
FNAPI extern void UTIL_size_t_to_hex(size_t value,
									 char buffer[SIZE_T_HEX_BUFSIZE]);


/* =============================== 12-array.h =============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* String array structure. */
typedef struct UTIL_StrArray
{
	size_t size;            /* Current number of elements. */
	size_t capacity;        /* Current capacity. */
	UTIL_StringBuffer *arr; /* Array of strings. */
} UTIL_StrArray;

/* Initialize string array ARR with initial capacity of INITIAL_CAPACITY. */
FNAPI extern RESULT_void UTIL_str_array_init(UTIL_StrArray *arr,
											 size_t initial_capacity);

/* Append string DATA to string array ARR.*/
FNAPI extern RESULT_void UTIL_str_array_append(UTIL_StrArray *arr,
											   UTIL_ConstString data);

/* Check if DATA is in string array ARR. Return 1 if found, 0 if not found or on
   error. */
FNAPI extern UTIL_Bool UTIL_str_in_array(UTIL_ConstString data,
										 UTIL_StrArray *arr);

/* Free all resources associated with string array ARR. */
FNAPI extern void UTIL_str_array_free(UTIL_StrArray *arr);



/* ================================ 13-fmt.h ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/*
  Simple formatter supporting placeholders %1 .. %9 and escaped percent %%
  Behavior and constraints (design choices explained in comments below):
   - Only supports placeholders %1 .. %9 (single digit).
   - "%%" emits a single '%' and consumes no argument.
   - For safety (to avoid reading past provided varargs) this implementation
	 treats a NULL vararg pointer as the end-of-arguments sentinel:
	   e.g. FMT_format("a=%1 b=%2", "x", "y", NULL) -> OK
	   if the caller provides fewer args and does NOT provide a NULL sentinel,
	   reading further via va_arg would be undefined. To avoid that undefined
	   behavior, we stop reading args when we see a NULL.
	 This means callers who want to pass an actual NULL as an argument cannot
	 do so with this implementation (trade-off for safety per request).
   - If a format contains a placeholder %n (1..9) but the caller did not
	 provide that many arguments (we determined provided args by stopping at the
	 first NULL or after the highest digit referenced up to 9), then we do NOT
	 substitute it; instead we emit the literal characters "%n". This avoids
	 consuming/reading non-existent arguments.

  Note: Because standard C varargs have no built-in count, the safest practical
  approach is to require a NULL sentinel if the caller may provide fewer
  arguments than the highest placeholder referenced. Example usage:
	FMT_format("%1-%2-%3", "a", "b", "c");              // ok
	FMT_format("%1-%2-%3-%4", "a", "b", "c", NULL);     // ok, %4 won't be
  formatted

  The function FMT_vformat formats a string using the given format specifier and
  a va_list of arguments. The formatted string is stored in the buffer pointed
  to by BUFFER. If BUFFER is NULL, the function returns the required buffer size
  (including terminating NUL) without formatting. */
FNAPI extern RESULT_void FMT_vformat(UTIL_StringBuffer *buffer,
									 UTIL_ConstString fmt, va_list ap);

/* Formats a string using the given format specifier and arguments. Stores the
   result in BUFFER. */
FNAPI extern RESULT_void FMT_format(UTIL_StringBuffer *buffer,
									UTIL_ConstString fmt, ...);



/* ================================ 14-map.h ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* A string:any map node. */
typedef struct MAP_Node
{
	UTIL_StringBuffer key; /* Malloc-allocated string key. */
	void *value;           /* Malloc-allocated value. */
	struct MAP_Node
		*next; /* Next node in bucket (linked list for collision resolution). */
	UTIL_UInt16 hash; /* Cached hash value to avoid recomputation. */
} MAP_Node;

/* Pointer to MAP_Node. */
typedef MAP_Node *MAP_NodePtr;

/* Result<MAP_NodePtr>. */
typedef struct RESULT_MAP_NodePtr
{
	UTIL_Bool has_value;
	union {
		struct EXC_ErrorCode error;
		MAP_NodePtr value;
	} result;
} RESULT_MAP_NodePtr;
FNAPI extern RESULT_MAP_NodePtr RESULT_error_MAP_NodePtr(
	int code, enum EXC_ErrorCategory category);
FNAPI extern RESULT_MAP_NodePtr RESULT_error_MAP_NodePtr_struct(
	struct EXC_ErrorCode error);
FNAPI extern RESULT_MAP_NodePtr RESULT_ok_MAP_NodePtr(MAP_NodePtr value);

/* A string:any map. */
typedef struct MAP_Map
{
	struct MAP_Node **buckets;  /* Array of buckets. */
	UTIL_UInt16 capacity;       /* Capacity (2^capacity_power). */
	UTIL_UInt16 size;           /* Current number of elements. */
	UTIL_UInt16 capacity_power; /* Exponent of capacity (capacity = 1 <<
								capacity_power). */
} MAP_Map;

/* Create a new MAP_Map to MAP with initial capacity 2^INIT_CAPACITY_POWER.
   Notice that INIT_CAPACITY_POWER must be in range [4, 14], and you should
   pre-allocate memory for the map struct. */
FNAPI extern RESULT_void MAP_create(MAP_Map *map,
									UTIL_UInt16 init_capacity_power);

/* Set a key-value pair in the MAP. If the KEY already exists, update its value.
   Notice that the KEY and VALUE **MUST** be malloc-allocated and the map will
   take ownership of them. */
FNAPI extern RESULT_void MAP_set(MAP_Map *map, UTIL_StringBuffer key,
								 void *value);

/* Get the value associated with the given KEY in the MAP. Returns NULL if the
   KEY is not found. Don't free the returned value because it is managed by the
   MAP. */
FNAPI extern const void *MAP_get(const MAP_Map *map, UTIL_ConstString key);

/* Check if the MAP contains the given KEY. Returns UTIL_TRUE if found,
   UTIL_FALSE otherwise. */
FNAPI extern UTIL_Bool MAP_contains(const MAP_Map *map, UTIL_ConstString key);

/* Remove the key-value pair with the given KEY from the MAP. If the KEY does
   not exist, nothing will happen. */
FNAPI extern void MAP_remove(MAP_Map *map, UTIL_ConstString key);

/* Clear all key-value pairs in the MAP. But do not free the MAP's bucket array.
 */
FNAPI extern void MAP_clear(MAP_Map *map);

/* Free all resources associated with the MAP. But do not free the MAP structure
   itself. It may be stack-allocated. */
FNAPI extern void MAP_free(MAP_Map *map);



/* ============================== 15-logging.h ============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Logging level. */
typedef enum LOGGING_LogLevel
{
	LOG_LEVEL_INVALID = -1,

	/* Debug level. */
	LOG_LEVEL_DEBUG = 0,
	/* Info level. */
	LOG_LEVEL_INFO = 1,
	/* Warning level. */
	LOG_LEVEL_WARN = 2,
	/* Error level. */
	LOG_LEVEL_ERROR = 3,

	LOG_LEVEL_MAX
} LOGGING_LogLevel;

/* Logger handler structure. */
typedef struct LOGGING_LoggerHandler
{
	/* Debug level handler. */
	void (*debug_handler)(UTIL_ConstString subject, UTIL_ConstString fmt,
						  va_list args);

	/* Info level handler. */
	void (*info_handler)(UTIL_ConstString subject, UTIL_ConstString fmt,
						 va_list args);

	/* Warning level handler. */
	void (*warn_handler)(UTIL_ConstString subject, UTIL_ConstString fmt,
						 va_list args);

	/* Error level handler. */
	void (*error_handler)(UTIL_ConstString subject, UTIL_ConstString fmt,
						  va_list args);

	/* Set logging level. */
	void (*set_level)(LOGGING_LogLevel level);
} LOGGING_LoggerHandler;

/* Initialize logging module. */
FNAPI extern void LOGGING_initialize(void);

/* Deinitialize logging module. */
FNAPI extern void LOGGING_deinitialize(void);

/* Set logging level. */
FNAPI extern void LOGGING_set_level(LOGGING_LogLevel level);

/* Convert logging level to string. */
FNAPI extern UTIL_ConstString LOGGING_log_level_tostring(
	LOGGING_LogLevel level);

/* Log a debug message with format FMT. */
FNAPI extern void LOGGING_debug(UTIL_ConstString subject, UTIL_ConstString fmt,
								...);

/* Log an info message with format FMT. */
FNAPI extern void LOGGING_info(UTIL_ConstString subject, UTIL_ConstString fmt,
							   ...);

/* Log a warning message with format FMT. */
FNAPI extern void LOGGING_warn(UTIL_ConstString subject, UTIL_ConstString fmt,
							   ...);

/* Log an error message with format FMT. */
FNAPI extern void LOGGING_error(UTIL_ConstString subject, UTIL_ConstString fmt,
								...);



/* ================================ 16-net.h ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Network socket type. */
typedef int NET_Socket;

/* Result<NET_Socket>. */
typedef struct RESULT_NET_Socket
{
	UTIL_Bool has_value;
	union {
		struct EXC_ErrorCode error;
		NET_Socket value;
	} result;
} RESULT_NET_Socket;
FNAPI extern RESULT_NET_Socket RESULT_error_NET_Socket(
	int code, enum EXC_ErrorCategory category);
FNAPI extern RESULT_NET_Socket RESULT_error_NET_Socket_struct(
	struct EXC_ErrorCode error);
FNAPI extern RESULT_NET_Socket RESULT_ok_NET_Socket(NET_Socket value);

	/* Invalid socket constant. */
	#define NET_INVALID_SOCKET (NET_Socket)(-1)

/* Internet protocol version. */
typedef enum NET_InetVersion
{
	/* IPv4 */
	NET_INET_VERSION_4 = AF_INET,
	#if USE_IPv6
	/* IPv6 */
	NET_INET_VERSION_6 = AF_INET6
	#endif /* USE_IPv6 */
} NET_InetVersion;

/* Internet address structures in local byte order. */
typedef UTIL_UInt8 NET_Inet4Addr[4];

	#if USE_IPv6
/* IPv6 address as an array of 8 16-bit segments in local byte order. */
typedef UTIL_UInt16 NET_Inet6Addr[8];
	#endif /* USE_IPv6 */

/* Generic internet address structure. */
typedef struct NET_InetAddr
{
	/* Internet protocol version. */
	NET_InetVersion version;
	union {
		/* IPv4 address. */
		NET_Inet4Addr inet4;
	#if USE_IPv6
		/* IPv6 address. */
		NET_Inet6Addr inet6;
	#endif /* USE_IPv6 */
	} addr;
} NET_InetAddr;

/* Initialize the networking module. */
FNAPI extern RESULT_void NET_initialize(void);

/* Deinitialize the networking subsystem. */
FNAPI extern RESULT_void NET_deinitialize(void);

/* Close a network socket. */
FNAPI extern void NET_closesocket(NET_Socket sock);

/* Create an asynchronous socket for the given internet version INET_VERSION. */
FNAPI extern RESULT_NET_Socket NET_async_socket(NET_InetVersion inet_version);

/* Convert the internet address ADDR to a string representation in OUT_BUF. */
FNAPI extern void NET_repr_inet_addr(const NET_InetAddr *addr,
									 UTIL_StringBuffer out_buf,
									 size_t out_buf_len);

	/* Maximum length of a string representation of an internet address. */
	#define NET_ADDR_REPR_MAX_LENGTH 46

/* Receive data from a socket SK, storing the source address and port in
   SRC_ADDR and SRC_PORT. */
FNAPI extern RESULT_UTIL_SignedSize NET_recvfrom(NET_Socket sock, void *buf,
												 size_t len, int flags,
												 NET_InetAddr *src_addr,
												 UTIL_UInt16 *src_port);

/* Send data to the specified destination address and port. */
FNAPI extern RESULT_void NET_sendto(NET_Socket sock, const void *buf,
									size_t len, int flags,
									const NET_InetAddr *dest_addr,
									UTIL_UInt16 dest_port);

/* Check if the error code ERR indicates a temporary failure (EAGAIN). */
FNAPI extern UTIL_Bool NET_need_try_again(EXC_ErrorCode err);



/* ============================= Directory: src ============================= */
/* =============================== 11-utils.c =============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


_FNAPI_EXPORT void *UTIL_memdup(const void *src, size_t n)
{
	void *dst;

	if (src == NULL || n == 0) return NULL;

	dst = malloc(n);
	if (dst == NULL) return NULL;

	memcpy(dst, src, n);

	return dst;
}

_FNAPI_EXPORT UTIL_StringBuffer UTIL_strdup(const char *src)
{
	return (UTIL_StringBuffer)UTIL_memdup((src), strlen(src) + 1);
}

_FNAPI_EXPORT RESULT_UTIL_SignedSize UTIL_vsprintf(UTIL_StringBuffer *buffer,
												   UTIL_ConstString fmt,
												   va_list args)
{
	RESULT_UTIL_SignedSize ret;
	UTIL_SignedSize res;
	UTIL_StringBuffer tmp_buffer;
	va_list ap_len;
	va_list ap_write;

	ret = RESULT_ok_UTIL_SignedSize(0);
	tmp_buffer = NULL;

	if (buffer == NULL || fmt == NULL)
		return RESULT_error_UTIL_SignedSize(EINVAL, EXC_CATEGORY_LIBC);

	*buffer = NULL;

	va_copy(ap_len, args);
	EXC_clear_last_error(EXC_CATEGORY_LIBC);
	res = (UTIL_SignedSize)vsnprintf(NULL, 0, fmt, ap_len);
	va_end(ap_len);
	if (res < 0)
	{
		ret = RESULT_ERRNO(UTIL_SignedSize, EXC_CATEGORY_LIBC);
		goto FAIL;
	}

	tmp_buffer = (UTIL_StringBuffer)malloc((size_t)res + 1);
	if (!tmp_buffer)
	{
		ret = RESULT_error_UTIL_SignedSize(ENOMEM, EXC_CATEGORY_LIBC);
		goto FAIL;
	}

	va_copy(ap_write, args);
	EXC_clear_last_error(EXC_CATEGORY_LIBC);
	res = vsnprintf(tmp_buffer, res + 1, fmt, ap_write);
	va_end(ap_write);
	if (res < 0)
	{
		ret = RESULT_ERRNO(UTIL_SignedSize, EXC_CATEGORY_LIBC);
		goto FAIL;
	}

	*buffer = tmp_buffer;

	goto EXIT;

FAIL:
	free(tmp_buffer);
EXIT:
	return ret;
}

#if HAS_WINDOWS
_FNAPI_EXPORT void UTIL_sleep_ms(UTIL_Time ms)
{
	if (ms == 0)
	{
		return;
	}

	Sleep((DWORD)ms);
}

_FNAPI_EXPORT UTIL_Time UTIL_get_current_time_ms(void)
{
	FILETIME ft;
	ULARGE_INTEGER uli;

	GetSystemTimeAsFileTime(&ft);
	uli.LowPart = ft.dwLowDateTime;
	uli.HighPart = ft.dwHighDateTime;

	/* Convert to milliseconds. */
	return (UTIL_Time)(uli.QuadPart / 10000);
}
#else
_FNAPI_EXPORT void UTIL_sleep_ms(UTIL_Time ms)
{
	struct timespec ts;

	if ((time_t)ms <= 0)
	{
		return;
	}

	ts.tv_sec = (time_t)(ms / 1000);
	ts.tv_nsec = (time_t)(ms % 1000) * 1000000;

	nanosleep(&ts, NULL);
}

_FNAPI_EXPORT UTIL_Time UTIL_get_current_time_ms(void)
{
	struct timespec ts;

	if (clock_gettime(CLOCK_REALTIME, &ts) != 0)
	{
		perror("WHY clock_gettime FAIL? ABORTING!");
		abort();
	}

	return (UTIL_Time)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}
#endif /* HAS_WINDOWS */

_FNAPI_EXPORT void UTIL_timer_start(struct UTIL_Timer *timer)
{
	if (timer == NULL) return;

	timer->start_time = UTIL_get_current_time_ms();
	timer->duration_ms = 0;
}

_FNAPI_EXPORT void UTIL_timer_reset(struct UTIL_Timer *timer)
{
	if (timer == NULL) return;

	timer->start_time = UTIL_get_current_time_ms();
	timer->duration_ms = 0;
}

_FNAPI_EXPORT UTIL_Time UTIL_timer_elapsed_ms(struct UTIL_Timer *timer)
{
	UTIL_Time now;

	if (timer == NULL) return 0;

	now = UTIL_get_current_time_ms();
	return now - timer->start_time;
}

_FNAPI_EXPORT UTIL_Bool UTIL_timer_ontime(struct UTIL_Timer *timer,
										  UTIL_Time duration_ms)
{
	if (timer == NULL) return UTIL_FALSE;

	return UTIL_timer_elapsed_ms(timer) >= duration_ms ? UTIL_TRUE : UTIL_FALSE;
}

/* CRC16-CCITT polynomial. */
static const UTIL_UInt16 UTIL_CRC16_CCITT_POLY = 0x1021;
UTIL_THREAD_LOCAL static UTIL_UInt16 g_UTIL_crc16_table[256];

_FNAPI_EXPORT void UTIL_initialize(void)
{
	int i;
	int j;
	UTIL_UInt16 crc;
	UTIL_THREAD_LOCAL static UTIL_Bool g_UTIL_crc16_table_initialized =
		UTIL_FALSE;

	if (g_UTIL_crc16_table_initialized) return;

	for (i = 0; i < 256; ++i)
	{
		crc = (UTIL_UInt16)i << 8;
		for (j = 0; j < 8; ++j)
		{
			if (crc & 0x8000)
				crc = (UTIL_UInt16)((crc << 1) ^ UTIL_CRC16_CCITT_POLY);
			else
				crc = (UTIL_UInt16)(crc << 1);
		}
		g_UTIL_crc16_table[i] = crc;
	}

	g_UTIL_crc16_table_initialized = UTIL_TRUE;
}

_FNAPI_EXPORT UTIL_UInt16 UTIL_str_hash(UTIL_ConstString key,
										UTIL_UInt16 table_size_2power)
{
	UTIL_register UTIL_UInt16 crc;

	crc = 0xFFFF;

	while (*key)
	{
		crc = (UTIL_UInt16)((crc << 8) ^
							g_UTIL_crc16_table[((crc >> 8) ^ (*key++)) &
											   0xFF]); /* Can't understand. */
	}

	/* Only available when table_size_2power is a power of 2. */
	return (UTIL_UInt16)(crc & (table_size_2power - 1));
}

_FNAPI_EXPORT UTIL_Bool UTIL_is_file(UTIL_ConstString path)
{
	FILE *file;
#if HAS_SAFE_C_LIB
	errno_t sc_err;
#endif

	if (path == NULL) return UTIL_FALSE;

	file = NULL;

#if HAS_SAFE_C_LIB
	sc_err = fopen_s(&file, path, "rb");
	if (sc_err != 0) return UTIL_FALSE;
#else
	file = fopen(path, "r");
	if (file == NULL) return UTIL_FALSE;
#endif

	fclose(file);
	return UTIL_TRUE;
}

/* Maximum value for size_t divided by 10. */
static const UTIL_UInt64 SIZE_T_MAX_DIV10 = UITL_SIZE_MAX / 10;

_FNAPI_EXPORT RESULT_size_t UTIL_str_to_unsigned_base10(UTIL_ConstString str)
{
	size_t result;
	int digit;

	if (str == NULL) return RESULT_error_size_t(EINVAL, EXC_CATEGORY_LIBC);

	result = 0;

	/* Skip leading whitespace. */
	while (isspace((int)(unsigned char)*str))
	{
		str++;
	}

	if (*str == '\0')
	{
		/* Empty string or only whitespace. */
		return RESULT_error_size_t(EINVAL, EXC_CATEGORY_LIBC);
	}

	while (*str)
	{
		if (!isdigit((unsigned char)*str))
		{
			/* Encountered non-digit character, return failure. */
			return RESULT_error_size_t(EINVAL, EXC_CATEGORY_LIBC);
		}

		digit = *str - '0'; /* Convert character to digit. */

		/* Check for overflow. */
		if (result > SIZE_T_MAX_DIV10 ||
			(result == SIZE_T_MAX_DIV10 && digit > 7))
		{
			/* Overflow case. */
			return RESULT_error_size_t(ERANGE, EXC_CATEGORY_LIBC);
		}

		/* Update result. */
		result = result * 10 + digit;

		str++;
	}

	return RESULT_ok_size_t(result);
}

_FNAPI_EXPORT void UTIL_size_t_to_hex(size_t value,
									  char buffer[SIZE_T_HEX_BUFSIZE])
{
	/* Buffer is guaranteed non-NULL and large enough. */
	static const char hexdig[] = "0123456789ABCDEF";

	char tmp[SIZE_T_HEX_BUFSIZE];
	int i;
	int j;
	int len;

	/* Special-case zero. */
	if (value == 0)
	{
		buffer[0] = '0';
		buffer[1] = '\0';
		return;
	}

	/* Convert into a temporary buffer from the end, then copy out. */
	i = (int)sizeof(tmp);
	while (value != 0)
	{
		tmp[--i] = hexdig[value & 0xF];
		value >>= 4;
	}

	len = (int)sizeof(tmp) - i;
	for (j = 0; j < len; ++j)
	{
		buffer[j] = tmp[i + j];
	}
	buffer[len] = '\0';
}


/* =============================== 12-array.c =============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


_FNAPI_EXPORT RESULT_void UTIL_str_array_init(UTIL_StrArray *arr,
											  size_t initial_capacity)
{
	if (arr == NULL || initial_capacity == 0)
		return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);

	arr->arr = (UTIL_StringBuffer *)malloc(sizeof(UTIL_StringBuffer) *
										   initial_capacity);
	if (arr->arr == NULL) return RESULT_error_void(ENOMEM, EXC_CATEGORY_LIBC);

	arr->size = 0;
	arr->capacity = initial_capacity;

	return RESULT_ok_void();
}

_FNAPI_EXPORT RESULT_void UTIL_str_array_append(UTIL_StrArray *arr,
												UTIL_ConstString data)
{
	UTIL_StringBuffer *new_arr;
	size_t new_capacity;

	if (arr == NULL || data == NULL)
		return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);

	if (arr->size >= arr->capacity)
	{
		new_capacity = arr->capacity * 2;
		new_arr = (UTIL_StringBuffer *)realloc(
			arr->arr, sizeof(UTIL_StringBuffer) * new_capacity);
		if (new_arr == NULL)
			return RESULT_error_void(ENOMEM, EXC_CATEGORY_LIBC);

		arr->arr = new_arr;
		arr->capacity = new_capacity;
	}

	arr->arr[arr->size] = UTIL_strdup(data);
	if (arr->arr[arr->size] == NULL)
		return RESULT_error_void(ENOMEM, EXC_CATEGORY_LIBC);

	arr->size++;
	return RESULT_ok_void();
}

_FNAPI_EXPORT UTIL_Bool UTIL_str_in_array(UTIL_ConstString data,
										  UTIL_StrArray *arr)
{
	size_t i;

	if (data == NULL || arr == NULL) return UTIL_FALSE;

	i = 0;

	while (i < arr->size)
	{
		if (strcmp(data, arr->arr[i]) == 0)
		{
			return UTIL_TRUE;
		}
		i++;
	}

	return UTIL_FALSE;
}

_FNAPI_EXPORT void UTIL_str_array_free(UTIL_StrArray *arr)
{
	size_t i;

	if (arr == NULL) return;

	for (i = 0; i < arr->size; i++)
	{
		free(arr->arr[i]);
	}

	free(arr->arr);
}


/* ================================ 13-fmt.c ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Maximum number of arguments supported. MUST <= 9 */
#define FMT_MAX_ARGS 9

/* (Internal) Count required buffer size (including terminating NUL) using
   pre-cached args. We do NOT consume a va_list here; instead, caller provides
   ARGVALS[] and provided count (number of valid entries). Placeholders
   referencing indices beyond provided args are emitted literally (as "%n").
   Returns -1 on error. */
static UTIL_SignedSize FMT__count_with_args(UTIL_ConstString fmt,
											UTIL_ConstString argvals[],
											int provided)
{
	UTIL_SignedSize ret;
	UTIL_ConstString p;
	size_t out_len;

	if (!fmt)
	{
		ret = -1;
		return ret;
	}

	out_len = 0;
	p = fmt;

	/* Compute output length. */
	while (*p)
	{
		if (*p == '%')
		{
			UTIL_ConstString q;

			if (p[1] == '%')
			{
				out_len += 1;
				p += 2;
				continue;
			}
			/* Attempt to parse index. */
			q = p + 1;
			if (isdigit((unsigned char)*q))
			{
				int idx;
				UTIL_ConstString r;

				idx = 0;
				r = q;
				while (*r && isdigit((unsigned char)*r))
				{
					idx = idx * 10 + (*r - '0');
					r++;
				}
				if (idx >= 1 && idx <= FMT_MAX_ARGS)
				{
					if (idx <= provided)
					{
						/* Substitute argument. */
						out_len += strlen(argvals[idx - 1]);
					}
					else
					{
						/* Do not substitute: emit literal "%<digits>". */
						out_len += (r - p);
					}
				}
				else
				{
					/* Index out of supported range: emit literal "%<digits>".
					 */
					out_len += (r - p);
				}
				p = r;
				continue;
			}
			else
			{
				/* '%' followed by non-digit: treat '%' literal. */
				out_len += 1;
				p++;
				continue;
			}
		}
		else
		{
			out_len += 1;
			p++;
		}
	}

	/* Include terminating NUL. */
	if (out_len >= (size_t)UTIL_SSIZE_MAX - 1)
	{
		ret = -1;
		return ret;
	}

	ret = (UTIL_SignedSize)(out_len + 1);
	return ret;
}

_FNAPI_EXPORT RESULT_void FMT_vformat(UTIL_StringBuffer *buffer,
									  UTIL_ConstString fmt, va_list ap)
{
	UTIL_StringBuffer buf;
	UTIL_SignedSize need;
	size_t bufsize;
	int max_idx;
	UTIL_ConstString argvals[FMT_MAX_ARGS];
	int provided;
	UTIL_ConstString p;
	UTIL_StringBuffer w;
	size_t remaining;
	int i;

	if (fmt == NULL || buffer == NULL) abort();

	/* Determine highest referenced index (1..9). */
	p = fmt;
	max_idx = 0;
	while (*p)
	{
		if (*p == '%')
		{
			UTIL_ConstString q;
			if (p[1] == '%')
			{
				p += 2;
				continue;
			}
			q = p + 1;
			if (isdigit((unsigned char)*q))
			{
				int idx;
				idx = 0;
				while (*q && isdigit((unsigned char)*q))
				{
					idx = idx * 10 + (*q - '0');
					q++;
				}
				if (idx >= 1 && idx <= FMT_MAX_ARGS)
				{
					if (idx > max_idx) max_idx = idx;
				}
				p = q;
				continue;
			}
			else
			{
				p++;
				continue;
			}
		}
		else
		{
			p++;
		}
	}

	/* Initialize argvals. */
	for (i = 0; i < FMT_MAX_ARGS; i++)
		argvals[i] = NULL;
	provided = 0;

	if (max_idx > 0)
	{
		/* Read arguments up to max_idx, stopping at first NULL sentinel. */
		for (i = 0; i < max_idx; i++)
		{
			UTIL_ConstString s;
			s = va_arg(ap, UTIL_ConstString);
			if (s == NULL)
			{
				/* Treat NULL as end-of-args sentinel. */
				break;
			}
			argvals[i] = s;
			provided++;
		}
	}

	/* Determine required size using cached args. */
	need = FMT__count_with_args(fmt, argvals, provided);
	if (need <= 0) return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);

	bufsize = (size_t)need;
	buf = (UTIL_StringBuffer)malloc(bufsize);
	if (buf == NULL) return RESULT_error_void(ENOMEM, EXC_CATEGORY_LIBC);

	/* Build the string into buf. */
	p = fmt;
	w = buf;
	remaining = bufsize; /* Includes room for terminating NUL. */

	while (*p)
	{
		if (*p == '%')
		{
			UTIL_ConstString q;

			if (p[1] == '%')
			{
				if (remaining < 2) goto ERR_FREE_BUF;
				*w++ = '%';
				remaining -= 1;
				p += 2;
				continue;
			}
			q = p + 1;
			if (isdigit((unsigned char)*q))
			{
				int idx;
				UTIL_ConstString r;

				idx = 0;
				r = q;
				while (*r && isdigit((unsigned char)*r))
				{
					idx = idx * 10 + (*r - '0');
					r++;
				}
				if (idx >= 1 && idx <= FMT_MAX_ARGS)
				{
					if (idx <= provided)
					{
						UTIL_ConstString s;
						size_t slen;

						s = argvals[idx - 1];
						slen = strlen(s);
						if (slen >= remaining) goto ERR_FREE_BUF;
						memcpy(w, s, slen);
						w += slen;
						remaining -= slen;
					}
					else
					{
						size_t litlen;

						litlen = (size_t)(r - p);
						if (litlen >= remaining) goto ERR_FREE_BUF;
						memcpy(w, p, litlen);
						w += litlen;
						remaining -= litlen;
					}
				}
				else
				{
					size_t litlen;

					litlen = (size_t)(r - p);
					if (litlen >= remaining) goto ERR_FREE_BUF;
					memcpy(w, p, litlen);
					w += litlen;
					remaining -= litlen;
				}
				p = r;
				continue;
			}
			else
			{
				if (remaining < 2) goto ERR_FREE_BUF;
				*w++ = '%';
				remaining -= 1;
				p++;
				continue;
			}
		}
		else
		{
			if (remaining < 2) goto ERR_FREE_BUF;
			*w++ = *p++;
			remaining -= 1;
		}
	}

	if (remaining < 1) goto ERR_FREE_BUF;
	*w = '\0';
	*buffer = buf;
	return RESULT_ok_void();

ERR_FREE_BUF:
	free(buf);
	return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);
}

_FNAPI_EXPORT RESULT_void FMT_format(UTIL_StringBuffer *buffer,
									 UTIL_ConstString fmt, ...)
{
	va_list ap;
	RESULT_void ret;

	va_start(ap, fmt);
	ret = FMT_vformat(buffer, fmt, ap);
	va_end(ap);

	return ret;
}


/* ================================ 14-map.c ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


_FNAPI_EXPORT RESULT_void MAP_create(MAP_Map *map,
									 UTIL_UInt16 init_capacity_power)
{
	RESULT_void ret;

	ret = RESULT_ok_void();

	if (map == NULL) return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);

	memset(map, 0, sizeof(MAP_Map));

	init_capacity_power = UTIL_min(UTIL_max(init_capacity_power, 4),
								   14); /* 16 <= capacity <= 16384 */

	map->capacity_power = init_capacity_power;
	map->capacity = 1 << init_capacity_power; /* pow(2, capacity_power) */
	map->size = 0;

	/* Allocate memory for bucket array. */
	map->buckets = (MAP_Node **)calloc(map->capacity, sizeof(MAP_Node *));
	if (!map->buckets)
	{
		ret = RESULT_error_void(ENOMEM, EXC_CATEGORY_LIBC);
		goto FAIL;
	}

	return ret;
FAIL:
	free(map->buckets);
	map->buckets = NULL;
	return ret;
}

/* (Internal) Resize the MAP to double its current capacity. */
static RESULT_void MAP__resize(MAP_Map *map)
{
	RESULT_void ret;
	UTIL_UInt16 old_capacity;
	MAP_Node **old_buckets;
	UTIL_UInt16 idx;

	ret = RESULT_ok_void();
	old_buckets = NULL;

	if (map->capacity_power >= 14)
	{
		/* Max capacity reached. */
		ret = RESULT_error_void(EFN_MAX_CAPACITY_EXCEEDED, EXC_CATEGORY_FN);
		goto EXIT;
	}

	if (map->size < map->capacity)
	{
		/* No need to resize. */
		goto EXIT;
	}

	old_capacity = map->capacity;
	old_buckets = map->buckets;

	/* Calculate new capacity (double). */
	map->capacity_power++;
	map->capacity = 1 << map->capacity_power;

	/* Allocate memory for new bucket array. */
	map->buckets = (MAP_Node **)calloc(map->capacity, sizeof(MAP_Node *));
	if (map->buckets == NULL)
	{
		map->buckets = old_buckets;
		map->capacity = old_capacity;
		map->capacity_power--;
		ret = RESULT_error_void(ENOMEM, EXC_CATEGORY_LIBC);
		goto EXIT;
	}

	/* Rehash all elements. */
	for (idx = 0; idx < old_capacity; idx++)
	{
		MAP_Node *node;

		node = old_buckets[idx];
		while (node)
		{
			MAP_Node *next;
			UTIL_UInt16 new_index;

			next = node->next;

			/* Reuse cached hash. */
			new_index = node->hash & (map->capacity - 1);

			/* Insert into new bucket (head insert). */
			node->next = map->buckets[new_index];
			map->buckets[new_index] = node;

			node = next;
		}
	}

	free(old_buckets);
EXIT:
	return ret;
}

/* (Internal) Create a new MAP_Node with the given KEY, VALUE, and HASH. If
   error, set libc error and return NULL. */
static RESULT_MAP_NodePtr MAP__create_node(UTIL_StringBuffer key, void *value,
										   UTIL_UInt16 hash)
{
	MAP_Node *node;

	if (key == NULL || value == NULL)
		return RESULT_error_MAP_NodePtr(EINVAL, EXC_CATEGORY_LIBC);

	node = (MAP_Node *)malloc(sizeof(MAP_Node));
	if (node == NULL)
		return RESULT_error_MAP_NodePtr(ENOMEM, EXC_CATEGORY_LIBC);

	node->key = key;

	node->value = value;
	node->hash = hash;
	node->next = NULL;

	return RESULT_ok_MAP_NodePtr(node);
}

/* Set a key-value pair in the MAP. If the KEY already exists, update its value.
   Notice that the KEY and VALUE **MUST** be malloc-allocated and the map will
   take ownership of them. */
_FNAPI_EXPORT RESULT_void MAP_set(MAP_Map *map, UTIL_StringBuffer key,
								  void *value)
{
	RESULT_void ret;
	UTIL_UInt16 hash;
	UTIL_UInt16 index;
	MAP_Node *node;
	MAP_Node *new_node;
	RESULT_MAP_NodePtr new_node_res;

	UTIL_initialize();
	ret = RESULT_ok_void();
	new_node = NULL;

	if (map == NULL || key == NULL || value == NULL)
		return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);

	/* Check if resizing is needed. */
	ret = MAP__resize(map);
	if (!ret.has_value) return ret;

	/* Calculate hash and index. */
	hash = UTIL_str_hash(key, map->capacity);
	index = hash; /* Already masked. */

	/* Check if key already exists. */
	node = map->buckets[index];
	while (node)
	{
		if (node->hash == hash && strcmp(node->key, key) == 0)
		{
			if (node->value != value)
			{
				free(node->value);
			}
			if (node->key != key)
			{
				free(node->key);
			}
			node->key = key;
			node->value = value;
			return ret; /* Updated existing key. */
		}
		node = node->next;
	}

	/* Create new node. */
	new_node_res = MAP__create_node(key, value, hash);
	if (!new_node_res.has_value)
		return RESULT_error_void_struct(new_node_res.result.error);

	new_node = new_node_res.result.value;

	/* Insert new node at the head of the bucket. */
	new_node->next = map->buckets[index];
	map->buckets[index] = new_node;
	map->size++;

	return ret;
}

/* Get the value associated with the given KEY in the MAP. Returns NULL if the
   KEY is not found. Don't free the returned value because it is managed by the
   MAP. */
_FNAPI_EXPORT const void *MAP_get(const MAP_Map *map, UTIL_ConstString key)
{
	UTIL_UInt16 hash;
	UTIL_UInt16 index;
	MAP_Node *node;

	UTIL_initialize();
	if (map == NULL || key == NULL) return NULL;

	hash = UTIL_str_hash(key, map->capacity);
	index = hash;

	node = map->buckets[index];
	while (node)
	{
		if (node->hash == hash && strcmp(node->key, key) == 0)
		{
			return node->value;
		}
		node = node->next;
	}

	return NULL; /* Not found. */
}

/* Check if the MAP contains the given KEY. */
_FNAPI_EXPORT UTIL_Bool MAP_contains(const MAP_Map *map, UTIL_ConstString key)
{
	UTIL_UInt16 hash;
	UTIL_UInt16 index;
	MAP_Node *node;

	UTIL_initialize();
	if (map == NULL || key == NULL) return UTIL_FALSE;

	hash = UTIL_str_hash(key, map->capacity);
	index = hash;

	node = map->buckets[index];
	while (node)
	{
		if (node->hash == hash && strcmp(node->key, key) == 0)
		{
			return UTIL_TRUE;
		}
		node = node->next;
	}

	return UTIL_FALSE; /* Not found. */
}

/* Remove the key-value pair with the given KEY from the MAP. If the KEY does
   not exist, nothing will happen. */
_FNAPI_EXPORT void MAP_remove(MAP_Map *map, UTIL_ConstString key)
{
	UTIL_UInt16 hash;
	UTIL_UInt16 index;
	MAP_Node *prev;
	MAP_Node *node;

	UTIL_initialize();
	if (map == NULL || key == NULL) return;

	hash = UTIL_str_hash(key, map->capacity);
	index = hash;

	prev = NULL;
	node = map->buckets[index];

	while (node)
	{
		if (node->hash == hash && strcmp(node->key, key) == 0)
		{
			/* Found node to remove. */
			if (prev)
			{
				prev->next = node->next;
			}
			else
			{
				map->buckets[index] = node->next;
			}

			/* Free node resources. */
			free(node->key);
			free(node->value);
			free(node);
			map->size--;

			return;
		}

		prev = node;
		node = node->next;
	}
}

/* Clear all key-value pairs in the MAP. But do not free the MAP's bucket array.
 */
_FNAPI_EXPORT void MAP_clear(MAP_Map *map)
{
	UTIL_UInt16 i;

	if (map == NULL) return;

	for (i = 0; i < map->capacity; i++)
	{
		MAP_Node *node;

		if (map->buckets == NULL) continue;

		node = map->buckets[i];
		while (node)
		{
			MAP_Node *next;

			if (node == NULL) continue;

			next = node->next;

			free(node->key);
			free(node->value);
			free(node);

			node = next;
		}
		map->buckets[i] = NULL;
	}

	map->size = 0;
}

/* Free all resources associated with the MAP. But do not free the MAP structure
   itself. It may be stack-allocated. */
_FNAPI_EXPORT void MAP_free(MAP_Map *map)
{
	if (map == NULL) return;

	MAP_clear(map);
	if (map->buckets) free(map->buckets);
}

/* Result<MAP_NodePtr>. */
_FNAPI_EXPORT RESULT_MAP_NodePtr
RESULT_error_MAP_NodePtr(int code, enum EXC_ErrorCategory category)
{
	RESULT_MAP_NodePtr result;
	result.has_value = UTIL_FALSE;
	result.result.error.code = code;
	result.result.error.category = category;
	return result;
}
_FNAPI_EXPORT RESULT_MAP_NodePtr
RESULT_error_MAP_NodePtr_struct(struct EXC_ErrorCode error)
{
	RESULT_MAP_NodePtr result;
	result.has_value = UTIL_FALSE;
	result.result.error = error;
	return result;
}
_FNAPI_EXPORT RESULT_MAP_NodePtr RESULT_ok_MAP_NodePtr(MAP_NodePtr value)
{
	RESULT_MAP_NodePtr result;
	result.has_value = UTIL_TRUE;
	result.result.value = value;
	return result;
}


/* ============================== 15-logging.c ============================== */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


UTIL_THREAD_LOCAL static LOGGING_LoggerHandler g_LOGGING__logger_handler;
UTIL_THREAD_LOCAL static LOGGING_LogLevel g_LOGGING__current_level =
	LOG_LEVEL_DEBUG;

static void LOGGING__set_cur_level(LOGGING_LogLevel level)
{
	g_LOGGING__current_level = level;
}

static UTIL_Bool LOGGING__is_valid_level(LOGGING_LogLevel level)
{
	return (level > LOG_LEVEL_INVALID && level < LOG_LEVEL_MAX) ? UTIL_TRUE
																: UTIL_FALSE;
}

_FNAPI_EXPORT void LOGGING_set_level(LOGGING_LogLevel level)
{
	LOGGING_initialize();

	if (LOGGING__is_valid_level(level) &&
		g_LOGGING__logger_handler.set_level != NULL)
	{
		g_LOGGING__logger_handler.set_level(level);
	}
}

_FNAPI_EXPORT UTIL_ConstString
LOGGING_log_level_tostring(LOGGING_LogLevel level)
{
	switch (level)
	{
	case LOG_LEVEL_DEBUG:
		return "DEBUG";
	case LOG_LEVEL_INFO:
		return "INFO";
	case LOG_LEVEL_WARN:
		return "WARN";
	case LOG_LEVEL_ERROR:
		return "ERROR";
	default:
		return "UNKNOWN";
	}
}

_FNAPI_EXPORT void LOGGING_debug(UTIL_ConstString subject, UTIL_ConstString fmt,
								 ...)
{
	va_list args;

	LOGGING_initialize();

	va_start(args, fmt);
	if (g_LOGGING__logger_handler.debug_handler != NULL)
		g_LOGGING__logger_handler.debug_handler(subject, fmt, args);
	va_end(args);
}

_FNAPI_EXPORT void LOGGING_info(UTIL_ConstString subject, UTIL_ConstString fmt,
								...)
{
	va_list args;

	LOGGING_initialize();

	va_start(args, fmt);
	if (g_LOGGING__logger_handler.info_handler != NULL)
		g_LOGGING__logger_handler.info_handler(subject, fmt, args);
	va_end(args);
}

_FNAPI_EXPORT void LOGGING_warn(UTIL_ConstString subject, UTIL_ConstString fmt,
								...)
{
	va_list args;

	LOGGING_initialize();

	va_start(args, fmt);
	if (g_LOGGING__logger_handler.warn_handler != NULL)
		g_LOGGING__logger_handler.warn_handler(subject, fmt, args);
	va_end(args);
}

_FNAPI_EXPORT void LOGGING_error(UTIL_ConstString subject, UTIL_ConstString fmt,
								 ...)
{
	va_list args;

	LOGGING_initialize();

	va_start(args, fmt);
	if (g_LOGGING__logger_handler.error_handler != NULL)
		g_LOGGING__logger_handler.error_handler(subject, fmt, args);
	va_end(args);
}

#if HAS_WINDOWS
UTIL_THREAD_LOCAL static HANDLE g_LOGGING__fd = INVALID_HANDLE_VALUE;

static UTIL_Bool LOGGING__isatty(void)
{
	DWORD mode;

	if (GetConsoleMode(g_LOGGING__fd, &mode))
	{
		return UTIL_TRUE;
	}

	return UTIL_FALSE;
}

enum LOGGING__Color
{
	LOGGING_COLOR_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	LOGGING_COLOR_RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
	LOGGING_COLOR_YELLOW =
		FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	LOGGING_COLOR_CYAN =
		FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
};

static void LOGGING__set_text_color(enum LOGGING__Color color)
{
	if (!LOGGING__isatty()) return;

	/* We can use ANSI escape to set text color. But Windows NT 4.0 don't
	   support it. */
	SetConsoleTextAttribute(g_LOGGING__fd, color);
}

static void LOGGING__writelog(UTIL_ConstString msg)
{
	DWORD written;

	if (g_LOGGING__fd == INVALID_HANDLE_VALUE) return;

	(void)WriteFile(g_LOGGING__fd, msg, (DWORD)strlen(msg), &written, NULL);
}
#else
static FILE *g_LOGGING__fd = NULL;

static UTIL_Bool LOGGING__isatty(void)
{
	return isatty(fileno(g_LOGGING__fd));
}

static const char *LOGGING_COLOR_WHITE = "\x1b[0;37m";
static const char *LOGGING_COLOR_RED = "\x1b[0;31m";
static const char *LOGGING_COLOR_YELLOW = "\x1b[0;33m";
static const char *LOGGING_COLOR_CYAN = "\x1b[0;36m";

static void LOGGING__set_text_color(const char *color)
{
	if (!LOGGING__isatty()) return;

	fprintf(g_LOGGING__fd, "%s", color);
}

static void LOGGING__writelog(UTIL_ConstString msg)
{
	fputs(msg, g_LOGGING__fd);
}
#endif /* HAS_WINDOWS */

static void LOGGING__logging_handler_v(LOGGING_LogLevel level,
									   UTIL_ConstString subject,
									   UTIL_ConstString fmt, va_list args)
{
	UTIL_StringBuffer buffer;
	UTIL_StringBuffer buffer2;
	char timebuf[SIZE_T_HEX_BUFSIZE];
	UTIL_Time now;

	buffer = NULL;
	buffer2 = NULL;
	now = UTIL_get_current_time_ms();

	UTIL_size_t_to_hex(now, timebuf);

	if (!UTIL_vsprintf(&buffer, fmt, args).has_value) goto EXIT;

	if (!FMT_format(&buffer2, "[%1 %2 0x%3] %4\n", subject,
					LOGGING_log_level_tostring(level), timebuf, buffer)
			 .has_value)
		goto EXIT;

	LOGGING__writelog(buffer2);

EXIT:
	free(buffer);
	free(buffer2);
}

static void LOGGING__debug_handler(UTIL_ConstString subject,
								   UTIL_ConstString fmt, va_list args)
{
	if (g_LOGGING__current_level > LOG_LEVEL_DEBUG) return;

	LOGGING__set_text_color(LOGGING_COLOR_CYAN);
	LOGGING__logging_handler_v(LOG_LEVEL_DEBUG, subject, fmt, args);
	LOGGING__set_text_color(LOGGING_COLOR_WHITE);
}

static void LOGGING__info_handler(UTIL_ConstString subject,
								  UTIL_ConstString fmt, va_list args)
{
	if (g_LOGGING__current_level > LOG_LEVEL_INFO) return;

	LOGGING__set_text_color(LOGGING_COLOR_WHITE);
	LOGGING__logging_handler_v(LOG_LEVEL_INFO, subject, fmt, args);
	LOGGING__set_text_color(LOGGING_COLOR_WHITE);
}

static void LOGGING__warn_handler(UTIL_ConstString subject,
								  UTIL_ConstString fmt, va_list args)
{
	if (g_LOGGING__current_level > LOG_LEVEL_WARN) return;

	LOGGING__set_text_color(LOGGING_COLOR_YELLOW);
	LOGGING__logging_handler_v(LOG_LEVEL_WARN, subject, fmt, args);
	LOGGING__set_text_color(LOGGING_COLOR_WHITE);
}

static void LOGGING__error_handler(UTIL_ConstString subject,
								   UTIL_ConstString fmt, va_list args)
{
	if (g_LOGGING__current_level > LOG_LEVEL_ERROR) return;

	LOGGING__set_text_color(LOGGING_COLOR_RED);
	LOGGING__logging_handler_v(LOG_LEVEL_ERROR, subject, fmt, args);
	LOGGING__set_text_color(LOGGING_COLOR_WHITE);
}

UTIL_THREAD_LOCAL static UTIL_Bool g_LOGGING__is_initialized = UTIL_FALSE;

_FNAPI_EXPORT void LOGGING_initialize(void)
{
	if (g_LOGGING__is_initialized) return;

#if HAS_WINDOWS
	g_LOGGING__fd = GetStdHandle(STD_ERROR_HANDLE);
#else
	g_LOGGING__fd = stderr;
#endif /* HAS_WINDOWS */

	g_LOGGING__logger_handler.debug_handler = LOGGING__debug_handler;
	g_LOGGING__logger_handler.info_handler = LOGGING__info_handler;
	g_LOGGING__logger_handler.warn_handler = LOGGING__warn_handler;
	g_LOGGING__logger_handler.error_handler = LOGGING__error_handler;
	g_LOGGING__logger_handler.set_level = LOGGING__set_cur_level;

	g_LOGGING__current_level = LOG_LEVEL_DEBUG;

	g_LOGGING__is_initialized = UTIL_TRUE;
}

_FNAPI_EXPORT void LOGGING_deinitialize(void)
{
	if (!g_LOGGING__is_initialized) return;

#if HAS_WINDOWS
	g_LOGGING__fd = INVALID_HANDLE_VALUE;
#else
	g_LOGGING__fd = NULL;
#endif /* HAS_WINDOWS */

	g_LOGGING__logger_handler.debug_handler = NULL;
	g_LOGGING__logger_handler.info_handler = NULL;
	g_LOGGING__logger_handler.warn_handler = NULL;
	g_LOGGING__logger_handler.error_handler = NULL;
	g_LOGGING__logger_handler.set_level = NULL;

	g_LOGGING__current_level = LOG_LEVEL_DEBUG;

	g_LOGGING__is_initialized = UTIL_FALSE;

	LOGGING__set_text_color(LOGGING_COLOR_WHITE);
}


/* ================================ 16-net.c ================================ */
/*
 * This file is part of the cppp-reiconv Library.
 *
 * The cppp-reiconv Library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * The cppp-reiconv Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the cppp-reiconv Library; see the file LICENSE.
 * If not, see <https://www.gnu.org/licenses/>.
 */


/* Result<NET_Socket>. */
_FNAPI_EXPORT RESULT_NET_Socket
RESULT_error_NET_Socket(int code, enum EXC_ErrorCategory category)
{
	RESULT_NET_Socket result;
	result.has_value = UTIL_FALSE;
	result.result.error.code = code;
	result.result.error.category = category;
	return result;
}
_FNAPI_EXPORT RESULT_NET_Socket
RESULT_error_NET_Socket_struct(struct EXC_ErrorCode error)
{
	RESULT_NET_Socket result;
	result.has_value = UTIL_FALSE;
	result.result.error = error;
	return result;
}
_FNAPI_EXPORT RESULT_NET_Socket RESULT_ok_NET_Socket(NET_Socket value)
{
	RESULT_NET_Socket result;
	result.has_value = UTIL_TRUE;
	result.result.value = value;
	return result;
}

_FNAPI_EXPORT void NET_repr_inet_addr(const NET_InetAddr *addr,
									  UTIL_StringBuffer out_buf,
									  size_t out_buf_len)
{
	if (addr->version == NET_INET_VERSION_4)
	{
		snprintf(out_buf, out_buf_len, "%u.%u.%u.%u", addr->addr.inet4[0],
				 addr->addr.inet4[1], addr->addr.inet4[2], addr->addr.inet4[3]);
	}
#if USE_IPv6
	else if (addr->version == NET_INET_VERSION_6)
	{
		snprintf(out_buf, out_buf_len, "%x:%x:%x:%x:%x:%x:%x:%x",
				 addr->addr.inet6[0], addr->addr.inet6[1], addr->addr.inet6[2],
				 addr->addr.inet6[3], addr->addr.inet6[4], addr->addr.inet6[5],
				 addr->addr.inet6[6], addr->addr.inet6[7]);
	}
#endif /* USE_IPv6 */
	else
		snprintf(out_buf, out_buf_len, "Unknown address family.");
}

/* Don't use sockaddr_storage because it's not available on WinNT 4.0. */
typedef UTIL_UInt8 NET_SockAddrStorage[UTIL_max(sizeof(struct sockaddr_in),
												sizeof(struct sockaddr_in6))];

/* Load port from system ADDR to FN's OUT_ADDR. */
static void NET__load_addr(struct sockaddr *addr, struct NET_InetAddr *out_addr)
{
	if (addr->sa_family == AF_INET)
	{
		struct sockaddr_in *addr_in;
		UTIL_UInt32 ip_host;

		addr_in = (struct sockaddr_in *)addr;
		out_addr->version = NET_INET_VERSION_4;
		ip_host = ntohl(addr_in->sin_addr.s_addr);

		out_addr->addr.inet4[0] = (UTIL_UInt8)((ip_host >> 24) & 0xFF);
		out_addr->addr.inet4[1] = (UTIL_UInt8)((ip_host >> 16) & 0xFF);
		out_addr->addr.inet4[2] = (UTIL_UInt8)((ip_host >> 8) & 0xFF);
		out_addr->addr.inet4[3] = (UTIL_UInt8)(ip_host & 0xFF);
	}
#if USE_IPv6
	else if (addr->sa_family == AF_INET6)
	{
		struct sockaddr_in6 *addr_in6;
		size_t i;
		UTIL_UInt16 segment;

		addr_in6 = (struct sockaddr_in6 *)addr;
		out_addr->version = NET_INET_VERSION_6;
		for (i = 0; i < 8; i++)
		{
			memcpy(&segment, &addr_in6->sin6_addr.s6_addr[i * 2],
				   sizeof(UTIL_UInt16));
			segment = ntohs(segment);
			out_addr->addr.inet6[i] = segment;
		}
	}
#endif /* USE_IPv6 */
	else
		LOGGING_error("NET", "NET_load_addr: Unsupported address family: %d",
					  addr->sa_family);
}

/* Load the port of a ADDR into OUT_PORT. */
static void NET__load_port(struct sockaddr *addr, UTIL_UInt16 *out_port)
{
	if (addr == NULL || out_port == NULL) return;

	if (addr->sa_family == AF_INET)
	{
		struct sockaddr_in *addr_in;

		addr_in = (struct sockaddr_in *)addr;
		*out_port = ntohs(addr_in->sin_port);
	}
#if USE_IPv6
	else if (addr->sa_family == AF_INET6)
	{
		struct sockaddr_in6 *addr_in6;

		addr_in6 = (struct sockaddr_in6 *)addr;
		*out_port = ntohs(addr_in6->sin6_port);
	}
#endif
	else
		LOGGING_error("NET", "NET_load_port: Unsupported address family: %d",
					  addr->sa_family);
}

_FNAPI_EXPORT UTIL_Bool NET_need_try_again(struct EXC_ErrorCode err)
{
	return (err.category == EXC_CATEGORY_FN) && (err.code == EFN_TRY_AGAIN);
}

#if HAS_WINDOWS
	#define NET__need_retry(err) (err == WSAEWOULDBLOCK)

static UTIL_Bool g_NET__wsa_initialized = UTIL_FALSE;

_FNAPI_EXPORT RESULT_void NET_initialize(void)
{
	WSADATA wsa_data;
	int result;

	if (g_NET__wsa_initialized) return RESULT_ok_void();

	result = WSAStartup(MAKEWORD(2, 2), &wsa_data);
	if (result != 0) return RESULT_error_void(result, EXC_CATEGORY_NET);

	g_NET__wsa_initialized = UTIL_TRUE;

	return RESULT_ok_void();
}

_FNAPI_EXPORT RESULT_void NET_deinitialize(void)
{
	int result;

	if (!g_NET__wsa_initialized) return RESULT_ok_void();

	result = WSACleanup();
	if (result != 0) return RESULT_error_void(result, EXC_CATEGORY_NET);

	g_NET__wsa_initialized = UTIL_FALSE;

	return RESULT_ok_void();
}

_FNAPI_EXPORT void NET_closesocket(NET_Socket sock)
{
	EXC_clear_last_error(EXC_CATEGORY_NET);
	if (closesocket(sock) == SOCKET_ERROR)
		LOGGING_warn("NET", "Failed to close socket: %s",
					 EXC_strerror(EXC_get_last_error(EXC_CATEGORY_NET)));
}

_FNAPI_EXPORT RESULT_NET_Socket NET_async_socket(NET_InetVersion inet_version)
{
	NET_Socket sock;
	u_long nonblock;

	EXC_clear_last_error(EXC_CATEGORY_NET);
	sock = (NET_Socket)WSASocket((int)inet_version, SOCK_DGRAM, IPPROTO_UDP,
								 NULL, 0, WSA_FLAG_OVERLAPPED);
	if (sock == INVALID_SOCKET)
		return RESULT_ERRNO(NET_Socket, EXC_CATEGORY_NET);

	/* Set the socket to non-blocking mode. */
	nonblock = 1;

	EXC_clear_last_error(EXC_CATEGORY_NET);
	if (ioctlsocket(sock, FIONBIO, &nonblock) == SOCKET_ERROR)
	{
		RESULT_NET_Socket err;
		err = RESULT_ERRNO(NET_Socket, EXC_CATEGORY_NET);
		NET_closesocket(sock);
		return err;
	}

	return RESULT_ok_NET_Socket(sock);
}

_FNAPI_EXPORT RESULT_UTIL_SignedSize NET_recvfrom(NET_Socket sock, void *buf,
												  size_t len, int flags,
												  NET_InetAddr *src_addr,
												  UTIL_UInt16 *src_port)
{
	UTIL_SignedSize received;
	NET_SockAddrStorage addr;
	int addr_len;

	if (src_addr == NULL || src_port == NULL || buf == NULL || len == 0)
		return RESULT_error_UTIL_SignedSize(EINVAL, EXC_CATEGORY_LIBC);

	addr_len = (int)sizeof(addr);
	memset(&addr, 0, sizeof(addr));

	EXC_clear_last_error(EXC_CATEGORY_NET);
	received = (UTIL_SignedSize)recvfrom(sock, buf, len, flags,
										 (struct sockaddr *)&addr, &addr_len);
	if (received < 0)
	{
		EXC_ErrorCode err;
		err = EXC_get_last_error(EXC_CATEGORY_NET);
		if (NET__need_retry(err.code)) /* Convert EAGAIN. */
		{
			return RESULT_error_UTIL_SignedSize(EFN_TRY_AGAIN, EXC_CATEGORY_FN);
		}
		return RESULT_error_UTIL_SignedSize_struct(err);
	}

	NET__load_addr((struct sockaddr *)&addr, src_addr);
	NET__load_port((struct sockaddr *)&addr, src_port);

	return RESULT_ok_UTIL_SignedSize(received);
}

_FNAPI_EXPORT RESULT_void NET_sendto(NET_Socket sock, const void *buf,
									 size_t len, int flags,
									 const NET_InetAddr *dest_addr,
									 UTIL_UInt16 dest_port)
{
	NET_SockAddrStorage addr;
	int addr_len;

	if (dest_addr == NULL || buf == NULL || len == 0)
		return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC);

	memset(&addr, 0, sizeof(addr));

	/* Fill in address structure. */
	if (dest_addr->version == NET_INET_VERSION_4)
	{
		struct sockaddr_in *addr_in;

		addr_in = (struct sockaddr_in *)&addr;
		addr_in->sin_family = AF_INET;
		addr_in->sin_port = htons(dest_port);
		addr_in->sin_addr.s_addr =
			htonl((UTIL_UInt32)dest_addr->addr.inet4[0] << 24 |
				  (UTIL_UInt32)dest_addr->addr.inet4[1] << 16 |
				  (UTIL_UInt32)dest_addr->addr.inet4[2] << 8 |
				  (UTIL_UInt32)dest_addr->addr.inet4[3]);
		addr_len = (int)sizeof(struct sockaddr_in);
	}
	else if (dest_addr->version == NET_INET_VERSION_6)
	{
		struct sockaddr_in6 *addr_in6;
		size_t i;

		addr_in6 = (struct sockaddr_in6 *)&addr;
		addr_in6->sin6_family = AF_INET6;
		addr_in6->sin6_port = htons(dest_port);
		for (i = 0; i < 8; i++)
		{
			UTIL_UInt16 segment;

			segment = htons(dest_addr->addr.inet6[i]);
			memcpy(&addr_in6->sin6_addr.s6_addr[i * 2], &segment,
				   sizeof(UTIL_UInt16));
		}
		addr_len = (int)sizeof(struct sockaddr_in6);
	}
	else
		return RESULT_error_void(EINVAL, EXC_CATEGORY_LIBC); /* Never happen. */

	if (sendto(sock, buf, len, flags, (struct sockaddr *)&addr, addr_len) < 0)
	{
		EXC_ErrorCode err;
		err = EXC_get_last_error(EXC_CATEGORY_NET);
		if (NET__need_retry(err.code)) /* Convert EAGAIN. */
		{
			return RESULT_error_void(EFN_TRY_AGAIN, EXC_CATEGORY_FN);
		}
		return RESULT_error_void_struct(err);
	}

	return RESULT_ok_void();
}
#else

#endif /* HAS_WINDOWS */


